version: "3.9"
services:
  redis:
    image: "redis:alpine"
    restart: on-failure
    ports:
      - "6379:6379"
  backend:
    restart: on-failure
    depends_on:
      - redis
    build: ./
    ports:
      - "5000:5000"
  worker:
    restart: on-failure
    depends_on:
      - redis
    build:
      context: ./
      dockerfile: worker.Dockerfile
